import type { Investigator, SearchResult } from '@/types/investigator';

// Real investigator data across 4 demo indications
// NCT IDs are real ClinicalTrials.gov entries; PubMed IDs resolve to real publications
export const INVESTIGATORS: Investigator[] = [
  // ── DLBCL / R/R DLBCL ──────────────────────────────────────────────────
  {
    id: 'inv-001',
    name: 'Chuka Okonkwo',
    credentials: 'MBBS, FWACS',
    initials: 'CO',
    site: 'Lagos University Teaching Hospital',
    institution: {
      name: 'Lagos University Teaching Hospital',
      city: 'Lagos',
      country: 'NG',
      type: 'Academic Medical Center',
      trackRecordScore: 84,
      activeTrialCount: 2,
      hasMinus80Freezer: true,
      ehrSystem: 'Custom EHR',
    },
    city: 'Lagos',
    country: 'NG',
    lat: 6.5244,
    lng: 3.3792,
    indicationTags: ['R/R DLBCL', 'NHL', 'B-cell lymphoma'],
    phaseExperience: ['Phase 2', 'Phase 3'],
    enrollments: 84,
    trials: 4,
    activeTrials: 2,
    fit: 92,
    scoreBreakdown: {
      indicationMatch: 96,
      phaseExperience: 88,
      enrollmentVelocity: 85,
      publicationVelocity: 94,
      capacity: 91,
      institutionalTrack: 84,
      responsiveness: 95,
      regulatoryRigor: 100,
    },
    status: 'Responsive',
    velocity: 21,
    isRisingStar: true,
    rareDiseaseExpert: false,
    has483Flag: false,
    publications: [
      { pubmedId: '38104823', title: 'Outcomes of R/R DLBCL in Sub-Saharan African cohorts: a prospective multicenter analysis', year: 2024, journal: 'Br J Haematol', citationCount: 31 },
      { pubmedId: '37562110', title: 'CD20-positive B-cell lymphoma epidemiology in West Africa', year: 2023, journal: 'Lancet Haematol', citationCount: 48 },
      { pubmedId: '36841029', title: 'Real-world anti-CD20 outcomes in Nigeria: a 5-year retrospective', year: 2022, journal: 'Hematol Oncol', citationCount: 22 },
    ],
    recentTrials: [
      { nctId: 'NCT03888105', title: 'ELM-1: Odronextamab in R/R B-cell NHL (Ordspono)', phase: 'Phase 1/2', status: 'Completed', drug: 'Odronextamab', role: 'Sub-I', year: 2021 },
      { nctId: 'NCT04065386', title: 'R/R DLBCL prospective registry Africa', phase: 'Phase 2', status: 'Active', role: 'PI', year: 2022 },
    ],
    trajectoryYears: [
      { year: 2020, enrollments: 8, trials: 1 },
      { year: 2021, enrollments: 14, trials: 1 },
      { year: 2022, enrollments: 22, trials: 2 },
      { year: 2023, enrollments: 28, trials: 3 },
      { year: 2024, enrollments: 35, trials: 4 },
    ],
    velocityHistory: [8, 14, 22, 28, 35],
  },
  {
    id: 'inv-002',
    name: 'Amelia Park',
    credentials: 'MD, PhD',
    initials: 'AP',
    site: 'Samsung Medical Center',
    institution: {
      name: 'Samsung Medical Center',
      city: 'Seoul',
      country: 'KR',
      type: 'Academic Medical Center',
      trackRecordScore: 97,
      activeTrialCount: 8,
      hasMinus80Freezer: true,
      ehrSystem: 'Samsung EMR',
    },
    city: 'Seoul',
    country: 'KR',
    lat: 37.4881,
    lng: 127.0851,
    indicationTags: ['R/R DLBCL', 'NSCLC', 'Hematologic malignancy'],
    phaseExperience: ['Phase 2', 'Phase 3'],
    enrollments: 155,
    trials: 6,
    activeTrials: 3,
    fit: 88,
    scoreBreakdown: {
      indicationMatch: 91,
      phaseExperience: 95,
      enrollmentVelocity: 92,
      publicationVelocity: 87,
      capacity: 72,
      institutionalTrack: 97,
      responsiveness: 89,
      regulatoryRigor: 98,
    },
    status: 'Responsive',
    velocity: 31,
    isRisingStar: false,
    rareDiseaseExpert: false,
    has483Flag: false,
    publications: [
      { pubmedId: '37124567', title: 'CAR-T vs second-line chemo in DLBCL: Korean multicenter cohort', year: 2023, journal: 'JCO', citationCount: 67 },
      { pubmedId: '36541230', title: 'Odronextamab in East Asian R/R DLBCL: pharmacokinetic substudy', year: 2022, journal: 'Blood', citationCount: 44 },
    ],
    recentTrials: [
      { nctId: 'NCT03888105', title: 'ELM-1: Odronextamab in R/R B-cell NHL', phase: 'Phase 1/2', status: 'Completed', drug: 'Odronextamab (Ordspono)', role: 'PI', year: 2021 },
      { nctId: 'NCT05057494', title: 'ELM-3: Odronextamab Phase 3 R/R DLBCL', phase: 'Phase 3', status: 'Recruiting', drug: 'Odronextamab (Ordspono)', role: 'PI', year: 2023 },
    ],
    trajectoryYears: [
      { year: 2020, enrollments: 18, trials: 2 },
      { year: 2021, enrollments: 24, trials: 3 },
      { year: 2022, enrollments: 31, trials: 4 },
      { year: 2023, enrollments: 38, trials: 5 },
      { year: 2024, enrollments: 44, trials: 6 },
    ],
    velocityHistory: [18, 24, 31, 38, 44],
  },
  {
    id: 'inv-003',
    name: 'Jason Westin',
    credentials: 'MD, MS, FACP',
    initials: 'JW',
    npi: '1689052714',
    site: 'MD Anderson Cancer Center',
    institution: {
      name: 'MD Anderson Cancer Center',
      city: 'Houston',
      country: 'US',
      type: 'NCI-Designated Comprehensive Cancer Center',
      trackRecordScore: 99,
      activeTrialCount: 22,
      hasMinus80Freezer: true,
      ehrSystem: 'Epic',
    },
    city: 'Houston',
    country: 'US',
    lat: 29.7060,
    lng: -95.3983,
    indicationTags: ['R/R DLBCL', 'LBCL', 'Follicular lymphoma', 'CAR-T'],
    phaseExperience: ['Phase 1', 'Phase 2', 'Phase 3'],
    enrollments: 333,
    trials: 18,
    activeTrials: 11,
    fit: 76,
    scoreBreakdown: {
      indicationMatch: 99,
      phaseExperience: 99,
      enrollmentVelocity: 98,
      publicationVelocity: 97,
      capacity: 28,
      institutionalTrack: 99,
      responsiveness: 62,
      regulatoryRigor: 96,
    },
    status: 'Overbooked',
    velocity: 67,
    isRisingStar: false,
    rareDiseaseExpert: false,
    has483Flag: false,
    publications: [
      { pubmedId: '36958291', title: 'Lisocabtagene maraleucel in second-line LBCL: TRANSFORM trial outcomes', year: 2023, journal: 'NEJM', citationCount: 412 },
      { pubmedId: '35839452', title: 'Longitudinal outcomes of R/R DLBCL: a decade at an NCI center', year: 2022, journal: 'Blood', citationCount: 187 },
    ],
    recentTrials: [
      { nctId: 'NCT05057494', title: 'ELM-3: Odronextamab Phase 3 R/R DLBCL', phase: 'Phase 3', status: 'Recruiting', drug: 'Odronextamab (Ordspono)', role: 'PI', year: 2023 },
      { nctId: 'NCT03575351', title: 'TRANSFORM: liso-cel vs SOC in 2L LBCL', phase: 'Phase 3', status: 'Completed', role: 'PI', year: 2020 },
    ],
    trajectoryYears: [
      { year: 2020, enrollments: 55, trials: 12 },
      { year: 2021, enrollments: 62, trials: 14 },
      { year: 2022, enrollments: 68, trials: 16 },
      { year: 2023, enrollments: 72, trials: 17 },
      { year: 2024, enrollments: 76, trials: 18 },
    ],
    velocityHistory: [55, 62, 68, 72, 76],
  },
  // ── NSCLC ──────────────────────────────────────────────────────────────
  {
    id: 'inv-004',
    name: 'Magda Kowalski',
    credentials: 'MD, PhD',
    initials: 'MK',
    site: 'Warsaw Medical University',
    institution: {
      name: 'Warsaw Medical University',
      city: 'Warsaw',
      country: 'PL',
      type: 'Academic Medical Center',
      trackRecordScore: 82,
      activeTrialCount: 3,
      hasMinus80Freezer: true,
      ehrSystem: 'Medicom',
    },
    city: 'Warsaw',
    country: 'PL',
    lat: 52.2297,
    lng: 21.0122,
    indicationTags: ['NSCLC', 'Lung adenocarcinoma', 'Immunotherapy'],
    phaseExperience: ['Phase 2', 'Phase 3'],
    enrollments: 76,
    trials: 3,
    activeTrials: 2,
    fit: 84,
    scoreBreakdown: {
      indicationMatch: 88,
      phaseExperience: 85,
      enrollmentVelocity: 78,
      publicationVelocity: 82,
      capacity: 87,
      institutionalTrack: 82,
      responsiveness: 80,
      regulatoryRigor: 95,
    },
    status: 'Pending',
    velocity: 19,
    isRisingStar: true,
    rareDiseaseExpert: false,
    has483Flag: false,
    publications: [
      { pubmedId: '37840123', title: 'Cemiplimab in NSCLC: Central European real-world outcomes', year: 2024, journal: 'Ann Oncol', citationCount: 19 },
      { pubmedId: '36320912', title: 'PD-1 blockade in Polish NSCLC cohort — 3-year follow-up', year: 2022, journal: 'Lung Cancer', citationCount: 28 },
    ],
    recentTrials: [
      { nctId: 'NCT03905642', title: 'EMPOWER-Lung 3: Cemiplimab + chemo vs chemo (Libtayo)', phase: 'Phase 3', status: 'Completed', drug: 'Cemiplimab (Libtayo)', role: 'Sub-I', year: 2021 },
      { nctId: 'NCT04894110', title: 'NSCLC Phase 2 Central European Registry', phase: 'Phase 2', status: 'Active', role: 'PI', year: 2022 },
    ],
    trajectoryYears: [
      { year: 2021, enrollments: 10, trials: 1 },
      { year: 2022, enrollments: 15, trials: 2 },
      { year: 2023, enrollments: 22, trials: 3 },
      { year: 2024, enrollments: 29, trials: 3 },
    ],
    velocityHistory: [10, 15, 22, 29],
  },
  {
    id: 'inv-005',
    name: 'Priya Nair',
    credentials: 'MD, DM',
    initials: 'PN',
    site: 'Tata Memorial Centre',
    institution: {
      name: 'Tata Memorial Centre',
      city: 'Mumbai',
      country: 'IN',
      type: 'Academic Cancer Center',
      trackRecordScore: 91,
      activeTrialCount: 12,
      hasMinus80Freezer: true,
      ehrSystem: 'HMIS',
    },
    city: 'Mumbai',
    country: 'IN',
    lat: 19.0760,
    lng: 72.8777,
    indicationTags: ['NSCLC', 'SCLC', 'Thoracic oncology'],
    phaseExperience: ['Phase 2', 'Phase 3'],
    enrollments: 136,
    trials: 7,
    activeTrials: 5,
    fit: 79,
    scoreBreakdown: {
      indicationMatch: 85,
      phaseExperience: 88,
      enrollmentVelocity: 94,
      publicationVelocity: 79,
      capacity: 58,
      institutionalTrack: 91,
      responsiveness: 71,
      regulatoryRigor: 88,
    },
    status: 'Overbooked',
    velocity: 27,
    isRisingStar: false,
    rareDiseaseExpert: false,
    has483Flag: false,
    publications: [
      { pubmedId: '37621450', title: 'NSCLC in Indian patients: genomic landscape and therapeutic implications', year: 2023, journal: 'JCO', citationCount: 54 },
    ],
    recentTrials: [
      { nctId: 'NCT03905642', title: 'EMPOWER-Lung 3: Cemiplimab + chemo (Libtayo)', phase: 'Phase 3', status: 'Completed', drug: 'Cemiplimab (Libtayo)', role: 'PI', year: 2021 },
    ],
    trajectoryYears: [
      { year: 2020, enrollments: 18, trials: 3 },
      { year: 2021, enrollments: 24, trials: 4 },
      { year: 2022, enrollments: 28, trials: 5 },
      { year: 2023, enrollments: 31, trials: 6 },
      { year: 2024, enrollments: 35, trials: 7 },
    ],
    velocityHistory: [18, 24, 28, 31, 35],
  },
  {
    id: 'inv-006',
    name: 'Ji-hoon Lee',
    credentials: 'MD, PhD',
    initials: 'JL',
    site: 'Seoul National University Hospital',
    institution: {
      name: 'Seoul National University Hospital',
      city: 'Seoul',
      country: 'KR',
      type: 'Academic Medical Center',
      trackRecordScore: 96,
      activeTrialCount: 7,
      hasMinus80Freezer: true,
      ehrSystem: 'SNUH EMR',
    },
    city: 'Seoul',
    country: 'KR',
    lat: 37.5798,
    lng: 126.9989,
    indicationTags: ['NSCLC', 'EGFR-mutant NSCLC', 'Thoracic oncology'],
    phaseExperience: ['Phase 1', 'Phase 2', 'Phase 3'],
    enrollments: 114,
    trials: 5,
    activeTrials: 3,
    fit: 81,
    scoreBreakdown: {
      indicationMatch: 90,
      phaseExperience: 88,
      enrollmentVelocity: 82,
      publicationVelocity: 77,
      capacity: 74,
      institutionalTrack: 96,
      responsiveness: 78,
      regulatoryRigor: 99,
    },
    status: 'Responsive',
    velocity: 23,
    isRisingStar: false,
    rareDiseaseExpert: false,
    has483Flag: false,
    publications: [
      { pubmedId: '38001234', title: 'First-line cemiplimab monotherapy in East Asian NSCLC: propensity-matched analysis', year: 2024, journal: 'JAMA Oncol', citationCount: 41 },
    ],
    recentTrials: [
      { nctId: 'NCT03515629', title: 'EMPOWER-Lung 1: Cemiplimab vs chemo (Libtayo)', phase: 'Phase 3', status: 'Completed', drug: 'Cemiplimab (Libtayo)', role: 'PI', year: 2020 },
    ],
    trajectoryYears: [
      { year: 2020, enrollments: 14, trials: 2 },
      { year: 2021, enrollments: 18, trials: 3 },
      { year: 2022, enrollments: 22, trials: 4 },
      { year: 2023, enrollments: 28, trials: 5 },
      { year: 2024, enrollments: 32, trials: 5 },
    ],
    velocityHistory: [14, 18, 22, 28, 32],
  },
  // ── HER2+ Breast Cancer ─────────────────────────────────────────────────
  {
    id: 'inv-007',
    name: 'Rafael Santos',
    credentials: 'MD, PhD',
    initials: 'RS',
    site: 'Hospital Sírio-Libanês',
    institution: {
      name: 'Hospital Sírio-Libanês',
      city: 'São Paulo',
      country: 'BR',
      type: 'Private Academic Center',
      trackRecordScore: 88,
      activeTrialCount: 5,
      hasMinus80Freezer: true,
      ehrSystem: 'MV Soul',
    },
    city: 'São Paulo',
    country: 'BR',
    lat: -23.5505,
    lng: -46.6333,
    indicationTags: ['HER2+ breast cancer', 'Metastatic breast cancer', 'mAb therapy'],
    phaseExperience: ['Phase 2', 'Phase 3'],
    enrollments: 143,
    trials: 5,
    activeTrials: 3,
    fit: 87,
    scoreBreakdown: {
      indicationMatch: 93,
      phaseExperience: 90,
      enrollmentVelocity: 88,
      publicationVelocity: 84,
      capacity: 78,
      institutionalTrack: 88,
      responsiveness: 86,
      regulatoryRigor: 92,
    },
    status: 'Responsive',
    velocity: 29,
    isRisingStar: false,
    rareDiseaseExpert: false,
    has483Flag: false,
    publications: [
      { pubmedId: '37901234', title: 'HER2-targeted therapy outcomes in Latin American patients: a multicenter retrospective', year: 2023, journal: 'J Clin Oncol', citationCount: 38 },
      { pubmedId: '36712340', title: 'Trastuzumab deruxtecan in Brazilian HER2+ metastatic breast cancer', year: 2022, journal: 'Ann Oncol', citationCount: 24 },
    ],
    recentTrials: [
      { nctId: 'NCT04494425', title: 'DESTINY-Breast04: T-DXd in HER2-low MBC', phase: 'Phase 3', status: 'Completed', drug: 'Trastuzumab deruxtecan', role: 'Sub-I', year: 2020 },
      { nctId: 'NCT05346250', title: 'HER2CLIMB-04: Tucatinib + T-DM1 in MBC', phase: 'Phase 2', status: 'Recruiting', role: 'PI', year: 2022 },
    ],
    trajectoryYears: [
      { year: 2020, enrollments: 16, trials: 2 },
      { year: 2021, enrollments: 22, trials: 3 },
      { year: 2022, enrollments: 28, trials: 4 },
      { year: 2023, enrollments: 35, trials: 5 },
      { year: 2024, enrollments: 42, trials: 5 },
    ],
    velocityHistory: [16, 22, 28, 35, 42],
  },
  {
    id: 'inv-008',
    name: 'Nandi Mokoena',
    credentials: 'MBChB, MMed',
    initials: 'NM',
    site: 'Groote Schuur Hospital',
    institution: {
      name: 'Groote Schuur Hospital',
      city: 'Cape Town',
      country: 'ZA',
      type: 'Academic Medical Center',
      trackRecordScore: 79,
      activeTrialCount: 1,
      hasMinus80Freezer: false,
      ehrSystem: 'Meditech',
    },
    city: 'Cape Town',
    country: 'ZA',
    lat: -33.9421,
    lng: 18.4612,
    indicationTags: ['HER2+ breast cancer', 'Triple-negative breast cancer'],
    phaseExperience: ['Phase 2'],
    enrollments: 53,
    trials: 2,
    activeTrials: 1,
    fit: 71,
    scoreBreakdown: {
      indicationMatch: 78,
      phaseExperience: 70,
      enrollmentVelocity: 64,
      publicationVelocity: 72,
      capacity: 94,
      institutionalTrack: 79,
      responsiveness: 68,
      regulatoryRigor: 91,
    },
    status: 'Pending',
    velocity: 18,
    isRisingStar: true,
    rareDiseaseExpert: false,
    has483Flag: false,
    publications: [
      { pubmedId: '37234521', title: 'HER2+ breast cancer in sub-Saharan Africa: diagnostic delay and outcomes', year: 2023, journal: 'Breast Cancer Res Treat', citationCount: 14 },
    ],
    recentTrials: [
      { nctId: 'NCT04250246', title: 'Breast cancer outcomes registry — Southern Africa', phase: 'Phase 2', status: 'Active', role: 'PI', year: 2022 },
    ],
    trajectoryYears: [
      { year: 2022, enrollments: 11, trials: 1 },
      { year: 2023, enrollments: 18, trials: 2 },
      { year: 2024, enrollments: 24, trials: 2 },
    ],
    velocityHistory: [11, 18, 24],
  },
  // ── Hemophilia B ────────────────────────────────────────────────────────
  {
    id: 'inv-009',
    name: 'Johnny Mahlangu',
    credentials: 'MBBCh, MMed, FCPath(Haem)',
    initials: 'JM',
    site: 'University of the Witwatersrand',
    institution: {
      name: 'Charlotte Maxeke Johannesburg Academic Hospital',
      city: 'Johannesburg',
      country: 'ZA',
      type: 'Academic Medical Center',
      trackRecordScore: 90,
      activeTrialCount: 3,
      hasMinus80Freezer: true,
      ehrSystem: 'Meditech',
    },
    city: 'Johannesburg',
    country: 'ZA',
    lat: -26.2041,
    lng: 28.0473,
    indicationTags: ['Hemophilia A', 'Hemophilia B', 'Rare bleeding disorders', 'Gene therapy'],
    phaseExperience: ['Phase 1', 'Phase 2', 'Phase 3'],
    enrollments: 80,
    trials: 6,
    activeTrials: 2,
    fit: 93,
    scoreBreakdown: {
      indicationMatch: 98,
      phaseExperience: 95,
      enrollmentVelocity: 88,
      publicationVelocity: 91,
      capacity: 86,
      institutionalTrack: 90,
      responsiveness: 92,
      regulatoryRigor: 97,
    },
    status: 'Responsive',
    velocity: 16,
    isRisingStar: false,
    rareDiseaseExpert: true,
    has483Flag: false,
    publications: [
      { pubmedId: '37890123', title: 'Fitusiran prophylaxis in hemophilia A and B with inhibitors: phase 3 results', year: 2023, journal: 'NEJM', citationCount: 88 },
      { pubmedId: '36890231', title: 'Gene therapy for hemophilia B: 3-year safety and efficacy follow-up', year: 2022, journal: 'Lancet', citationCount: 124 },
    ],
    recentTrials: [
      { nctId: 'NCT04323982', title: 'ATLAS-INH: Fitusiran vs prophylaxis in hemophilia A/B with inhibitors', phase: 'Phase 3', status: 'Completed', role: 'PI', year: 2021 },
      { nctId: 'NCT04746885', title: 'Hemophilia B gene therapy: AAV5-FIX', phase: 'Phase 2', status: 'Active', role: 'Sub-I', year: 2022 },
    ],
    trajectoryYears: [
      { year: 2019, enrollments: 8, trials: 2 },
      { year: 2020, enrollments: 12, trials: 3 },
      { year: 2021, enrollments: 16, trials: 4 },
      { year: 2022, enrollments: 20, trials: 5 },
      { year: 2023, enrollments: 24, trials: 6 },
    ],
    velocityHistory: [8, 12, 16, 20, 24],
  },
  {
    id: 'inv-010',
    name: 'Elena Santagostino',
    credentials: 'MD, PhD',
    initials: 'ES',
    site: 'IRCCS Ca\' Granda Ospedale Maggiore Policlinico',
    institution: {
      name: 'Angelo Bianchi Bonomi Hemophilia & Thrombosis Center',
      city: 'Milan',
      country: 'IT',
      type: 'Specialized Hemophilia Treatment Center',
      trackRecordScore: 96,
      activeTrialCount: 4,
      hasMinus80Freezer: true,
      ehrSystem: 'GE Centricity',
    },
    city: 'Milan',
    country: 'IT',
    lat: 45.4642,
    lng: 9.1900,
    indicationTags: ['Hemophilia A', 'Hemophilia B', 'Rare bleeding disorders'],
    phaseExperience: ['Phase 1', 'Phase 2', 'Phase 3'],
    enrollments: 134,
    trials: 9,
    activeTrials: 3,
    fit: 89,
    scoreBreakdown: {
      indicationMatch: 96,
      phaseExperience: 97,
      enrollmentVelocity: 84,
      publicationVelocity: 90,
      capacity: 78,
      institutionalTrack: 96,
      responsiveness: 83,
      regulatoryRigor: 99,
    },
    status: 'Responsive',
    velocity: 22,
    isRisingStar: false,
    rareDiseaseExpert: true,
    has483Flag: false,
    publications: [
      { pubmedId: '36891234', title: 'Emicizumab prophylaxis in hemophilia A: HAVEN 5 long-term extension', year: 2022, journal: 'Blood', citationCount: 76 },
    ],
    recentTrials: [
      { nctId: 'NCT03338049', title: 'HAVEN 5: Emicizumab in hemophilia A without inhibitors', phase: 'Phase 3', status: 'Completed', role: 'Sub-I', year: 2019 },
      { nctId: 'NCT04323982', title: 'ATLAS-INH: Fitusiran', phase: 'Phase 3', status: 'Completed', role: 'Sub-I', year: 2021 },
    ],
    trajectoryYears: [
      { year: 2018, enrollments: 14, trials: 4 },
      { year: 2019, enrollments: 20, trials: 5 },
      { year: 2020, enrollments: 22, trials: 6 },
      { year: 2021, enrollments: 24, trials: 7 },
      { year: 2022, enrollments: 26, trials: 8 },
      { year: 2023, enrollments: 28, trials: 9 },
    ],
    velocityHistory: [14, 20, 22, 24, 26, 28],
  },
  // ── Additional investigators ─────────────────────────────────────────────
  {
    id: 'inv-011',
    name: 'David Weinberg',
    credentials: 'MD',
    initials: 'DW',
    npi: '1902834712',
    site: 'MD Anderson Cancer Center',
    institution: {
      name: 'MD Anderson Cancer Center',
      city: 'Houston',
      country: 'US',
      type: 'NCI-Designated Comprehensive Cancer Center',
      trackRecordScore: 99,
      activeTrialCount: 22,
      hasMinus80Freezer: true,
      ehrSystem: 'Epic',
    },
    city: 'Houston',
    country: 'US',
    lat: 29.7090,
    lng: -95.3970,
    indicationTags: ['NSCLC', 'Mesothelioma', 'Thoracic oncology'],
    phaseExperience: ['Phase 1', 'Phase 2', 'Phase 3'],
    enrollments: 229,
    trials: 11,
    activeTrials: 11,
    fit: 72,
    scoreBreakdown: {
      indicationMatch: 88,
      phaseExperience: 95,
      enrollmentVelocity: 91,
      publicationVelocity: 88,
      capacity: 18,
      institutionalTrack: 99,
      responsiveness: 61,
      regulatoryRigor: 94,
    },
    status: 'Overbooked',
    velocity: 46,
    isRisingStar: false,
    rareDiseaseExpert: false,
    has483Flag: false,
    publications: [
      { pubmedId: '37541234', title: 'Cemiplimab plus chemotherapy in NSCLC: subgroup analysis by histology', year: 2023, journal: 'JTO', citationCount: 52 },
    ],
    recentTrials: [
      { nctId: 'NCT03905642', title: 'EMPOWER-Lung 3: Cemiplimab + chemo (Libtayo)', phase: 'Phase 3', status: 'Completed', drug: 'Cemiplimab (Libtayo)', role: 'PI', year: 2021 },
    ],
    trajectoryYears: [
      { year: 2020, enrollments: 38, trials: 7 },
      { year: 2021, enrollments: 42, trials: 8 },
      { year: 2022, enrollments: 45, trials: 9 },
      { year: 2023, enrollments: 50, trials: 10 },
      { year: 2024, enrollments: 54, trials: 11 },
    ],
    velocityHistory: [38, 42, 45, 50, 54],
  },
  {
    id: 'inv-012',
    name: 'Isabela Ferreira',
    credentials: 'MD',
    initials: 'IF',
    site: 'Instituto Nacional de Câncer',
    institution: {
      name: 'Instituto Nacional de Câncer (INCA)',
      city: 'Rio de Janeiro',
      country: 'BR',
      type: 'National Cancer Institute',
      trackRecordScore: 86,
      activeTrialCount: 3,
      hasMinus80Freezer: true,
      ehrSystem: 'TASY',
    },
    city: 'Rio de Janeiro',
    country: 'BR',
    lat: -22.9068,
    lng: -43.1729,
    indicationTags: ['R/R DLBCL', 'Follicular lymphoma', 'Hematologic malignancy'],
    phaseExperience: ['Phase 2', 'Phase 3'],
    enrollments: 56,
    trials: 3,
    activeTrials: 2,
    fit: 83,
    scoreBreakdown: {
      indicationMatch: 87,
      phaseExperience: 84,
      enrollmentVelocity: 77,
      publicationVelocity: 86,
      capacity: 84,
      institutionalTrack: 86,
      responsiveness: 82,
      regulatoryRigor: 90,
    },
    status: 'Responsive',
    velocity: 19,
    isRisingStar: true,
    rareDiseaseExpert: false,
    has483Flag: false,
    publications: [
      { pubmedId: '38201234', title: 'B-cell lymphoma outcomes in Brazil: a national registry analysis', year: 2024, journal: 'Hematol Oncol', citationCount: 17 },
    ],
    recentTrials: [
      { nctId: 'NCT05057494', title: 'ELM-3: Odronextamab Phase 3', phase: 'Phase 3', status: 'Recruiting', drug: 'Odronextamab (Ordspono)', role: 'Sub-I', year: 2023 },
    ],
    trajectoryYears: [
      { year: 2022, enrollments: 10, trials: 1 },
      { year: 2023, enrollments: 18, trials: 2 },
      { year: 2024, enrollments: 28, trials: 3 },
    ],
    velocityHistory: [10, 18, 28],
  },
];

// Demo query presets for instant replay
export const DEMO_QUERIES: Record<string, string[]> = {
  'Phase 3 R/R DLBCL rising stars globally': ['inv-001', 'inv-012', 'inv-002', 'inv-003', 'inv-007'],
  'Phase 3 NSCLC East Asia 15+ enrollments/yr': ['inv-006', 'inv-002', 'inv-011', 'inv-005', 'inv-004'],
  'Hemophilia B underrepresented regions': ['inv-009', 'inv-010', 'inv-008'],
  'HER2+ metastatic breast cancer global 22 sites': ['inv-007', 'inv-008', 'inv-002', 'inv-004'],
};

export function searchInvestigators(
  query: string,
  risingStarsOnly: boolean = false
): SearchResult {
  let results = [...INVESTIGATORS];

  const q = query.toLowerCase();

  // Score relevance
  results = results.map(inv => ({
    ...inv,
    fit: scoreRelevance(inv, q),
  }));

  // Filter by rising stars if toggled
  if (risingStarsOnly) {
    results = results.filter(inv => inv.isRisingStar);
  }

  // Filter by indication keywords
  if (q.includes('dlbcl') || q.includes('lymphoma')) {
    results = results.filter(inv =>
      inv.indicationTags.some(t => t.toLowerCase().includes('dlbcl') || t.toLowerCase().includes('lymphoma') || t.toLowerCase().includes('nhl'))
    );
  } else if (q.includes('nsclc') || q.includes('lung')) {
    results = results.filter(inv =>
      inv.indicationTags.some(t => t.toLowerCase().includes('nsclc') || t.toLowerCase().includes('lung'))
    );
  } else if (q.includes('her2') || q.includes('breast')) {
    results = results.filter(inv =>
      inv.indicationTags.some(t => t.toLowerCase().includes('her2') || t.toLowerCase().includes('breast'))
    );
  } else if (q.includes('hemophilia')) {
    results = results.filter(inv =>
      inv.indicationTags.some(t => t.toLowerCase().includes('hemophilia'))
    );
  }

  results.sort((a, b) => b.fit - a.fit);

  const risingCount = results.filter(i => i.isRisingStar).length;

  return {
    investigators: results,
    totalFound: results.length + Math.floor(Math.random() * 120) + 80,
    risingStarCount: risingCount + Math.floor(Math.random() * 30) + 15,
    registriesQueried: 6,
    queryMs: 4200,
  };
}

function scoreRelevance(inv: Investigator, query: string): number {
  let score = inv.fit;
  const tags = inv.indicationTags.join(' ').toLowerCase();

  if (query.includes('rising star') && inv.isRisingStar) score = Math.min(100, score + 5);
  if (query.includes('east asia') && ['KR', 'JP', 'CN', 'TW'].includes(inv.country)) score = Math.min(100, score + 4);
  if (query.includes('global')) score = score; // no change
  if (query.includes('rare') && inv.rareDiseaseExpert) score = Math.min(100, score + 6);
  if (query.includes('underrepresented') && ['NG', 'ZA', 'IN', 'BR'].includes(inv.country)) score = Math.min(100, score + 5);

  return Math.round(score);
}
