/**
 * Mock data for testing Rising Stars UI
 * Remove this file once you have real data in Supabase
 */

import type { RisingStar } from "@/types/rising-star";

export const mockRisingStars: RisingStar[] = [
  {
    name: "PARK, ANNSEA",
    institution: "YALE UNIVERSITY",
    state: "CT",
    orcidUrl: "https://orcid.org/0009-0005-0879-986X",
    grantId: "5F30AI157301-04",
    fiscalYear: 2024,
    researchTopics: ["autoimmune", "immunology"],
    compositeScore: 85,
    breakdown: {
      researchOutput: 75,
      clinicalExposure: 95,
      institutionalReadiness: 100,
    },
    signals: {
      totalPublications: 12,
      pubsLast3Years: 6,
      activeTrialsAtSite: 100,
      phase2PlusTrials: 64,
      investigatorTrialCount: 2,
    },
    dataCompleteness: 0.95,
    needsReview: false,
  },
  {
    name: "ZELASKO, SUSAN",
    institution: "UNIVERSITY OF WISCONSIN-MADISON",
    state: "WI",
    orcidUrl: "https://orcid.org/0000-0001-7318-585X",
    grantId: "5F30AI169759-02",
    fiscalYear: 2024,
    researchTopics: ["infectious disease", "virology"],
    compositeScore: 78,
    breakdown: {
      researchOutput: 60,
      clinicalExposure: 90,
      institutionalReadiness: 95,
    },
    signals: {
      totalPublications: 8,
      pubsLast3Years: 5,
      activeTrialsAtSite: 100,
      phase2PlusTrials: 60,
      investigatorTrialCount: 1,
    },
    dataCompleteness: 0.88,
    needsReview: false,
  },
  {
    name: "YAO, ANNIE Y",
    institution: "UNIVERSITY OF CONNECTICUT SCH OF MED/DNT",
    state: "CT",
    orcidUrl: null,
    grantId: "5F30AG081134-02",
    fiscalYear: 2024,
    researchTopics: ["alzheimer", "neurology", "neurodegeneration"],
    compositeScore: 52,
    breakdown: {
      researchOutput: 45,
      clinicalExposure: 55,
      institutionalReadiness: 65,
    },
    signals: {
      totalPublications: 5,
      pubsLast3Years: 3,
      activeTrialsAtSite: 45,
      phase2PlusTrials: 20,
      investigatorTrialCount: 0,
    },
    dataCompleteness: 0.72,
    needsReview: false,
  },
  {
    name: "CHEN, MICHAEL",
    institution: "STANFORD UNIVERSITY",
    state: "CA",
    orcidUrl: "https://orcid.org/0000-0002-1234-5678",
    grantId: "5F30CA250000-01",
    fiscalYear: 2023,
    researchTopics: ["oncology", "cancer", "tumor"],
    compositeScore: 92,
    breakdown: {
      researchOutput: 90,
      clinicalExposure: 95,
      institutionalReadiness: 100,
    },
    signals: {
      totalPublications: 18,
      pubsLast3Years: 10,
      activeTrialsAtSite: 150,
      phase2PlusTrials: 95,
      investigatorTrialCount: 3,
    },
    dataCompleteness: 1.0,
    needsReview: false,
  },
  {
    name: "RODRIGUEZ, MARIA",
    institution: "JOHNS HOPKINS UNIVERSITY",
    state: "MD",
    orcidUrl: "https://orcid.org/0000-0003-9876-5432",
    grantId: "5F30HL200000-02",
    fiscalYear: 2024,
    researchTopics: ["cardiology", "cardiovascular"],
    compositeScore: 67,
    breakdown: {
      researchOutput: 55,
      clinicalExposure: 75,
      institutionalReadiness: 80,
    },
    signals: {
      totalPublications: 7,
      pubsLast3Years: 4,
      activeTrialsAtSite: 85,
      phase2PlusTrials: 45,
      investigatorTrialCount: 1,
    },
    dataCompleteness: 0.83,
    needsReview: false,
  },
  {
    name: "JOHNSON, ROBERT",
    institution: "DUKE UNIVERSITY",
    state: "NC",
    orcidUrl: null,
    grantId: "5F30NS180000-01",
    fiscalYear: 2023,
    researchTopics: ["neurology"],
    compositeScore: 28,
    breakdown: {
      researchOutput: 20,
      clinicalExposure: 30,
      institutionalReadiness: 40,
    },
    signals: {
      totalPublications: 2,
      pubsLast3Years: 1,
      activeTrialsAtSite: 15,
      phase2PlusTrials: 5,
      investigatorTrialCount: 0,
    },
    dataCompleteness: 0.45,
    needsReview: true,
  },
  {
    name: "PATEL, PRIYA",
    institution: "UNIVERSITY OF CALIFORNIA-SAN FRANCISCO",
    state: "CA",
    orcidUrl: "https://orcid.org/0000-0004-5555-6666",
    grantId: "5F30DK195000-03",
    fiscalYear: 2022,
    researchTopics: ["diabetes", "endocrinology"],
    compositeScore: 71,
    breakdown: {
      researchOutput: 65,
      clinicalExposure: 75,
      institutionalReadiness: 85,
    },
    signals: {
      totalPublications: 10,
      pubsLast3Years: 6,
      activeTrialsAtSite: 92,
      phase2PlusTrials: 50,
      investigatorTrialCount: 2,
    },
    dataCompleteness: 0.91,
    needsReview: false,
  },
  {
    name: "WILLIAMS, SARAH",
    institution: "MASSACHUSETTS GENERAL HOSPITAL",
    state: "MA",
    orcidUrl: "https://orcid.org/0000-0005-7777-8888",
    grantId: "5F30AI175000-02",
    fiscalYear: 2023,
    researchTopics: ["immunology", "autoimmune", "rheumatology"],
    compositeScore: 88,
    breakdown: {
      researchOutput: 85,
      clinicalExposure: 90,
      institutionalReadiness: 95,
    },
    signals: {
      totalPublications: 15,
      pubsLast3Years: 8,
      activeTrialsAtSite: 120,
      phase2PlusTrials: 75,
      investigatorTrialCount: 4,
    },
    dataCompleteness: 0.97,
    needsReview: false,
  },
  {
    name: "NGUYEN, DAVID",
    institution: "UNIVERSITY OF MICHIGAN",
    state: "MI",
    orcidUrl: null,
    grantId: "5F30CA185000-01",
    fiscalYear: 2024,
    researchTopics: ["oncology", "rare disease"],
    compositeScore: 43,
    breakdown: {
      researchOutput: 35,
      clinicalExposure: 48,
      institutionalReadiness: 55,
    },
    signals: {
      totalPublications: 4,
      pubsLast3Years: 2,
      activeTrialsAtSite: 32,
      phase2PlusTrials: 12,
      investigatorTrialCount: 0,
    },
    dataCompleteness: 0.58,
    needsReview: true,
  },
  {
    name: "ANDERSON, EMILY",
    institution: "COLUMBIA UNIVERSITY",
    state: "NY",
    orcidUrl: "https://orcid.org/0000-0006-9999-0000",
    grantId: "5F30MH190000-02",
    fiscalYear: 2023,
    researchTopics: ["neurology", "neurodegeneration"],
    compositeScore: 76,
    breakdown: {
      researchOutput: 70,
      clinicalExposure: 80,
      institutionalReadiness: 85,
    },
    signals: {
      totalPublications: 11,
      pubsLast3Years: 7,
      activeTrialsAtSite: 95,
      phase2PlusTrials: 52,
      investigatorTrialCount: 2,
    },
    dataCompleteness: 0.89,
    needsReview: false,
  },
];
