/**
 * Audio Briefing — ElevenLabs integration
 *
 * Generates a 45-second spoken dossier for a clinical investigator.
 * Script generated by Claude Haiku, speech by ElevenLabs Turbo v2.5.
 */
import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';
import { INVESTIGATORS } from '@/lib/data';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const anthropic = new Anthropic();

// In-memory cache (per deployment instance — enough for demo)
const cache = new Map<string, { script: string; audioUrl: string; ts: number }>();
const CACHE_TTL = 30 * 60 * 1000; // 30 min

const RACHEL_VOICE_ID = '21m00Tcm4TlvDq8ikWAM';

export async function POST(req: NextRequest) {
  const { investigatorId } = await req.json().catch(() => ({}));

  if (!investigatorId) {
    return NextResponse.json({ error: 'investigatorId required' }, { status: 400 });
  }

  const hit = cache.get(investigatorId);
  if (hit && Date.now() - hit.ts < CACHE_TTL) {
    return NextResponse.json({ audioUrl: hit.audioUrl, script: hit.script, cached: true });
  }

  const inv = INVESTIGATORS.find(i => i.id === investigatorId);
  if (!inv) {
    return NextResponse.json({ error: 'Investigator not found' }, { status: 404 });
  }

  // ── 1. Generate briefing script with Claude Haiku ───────────────────────
  let script = '';
  try {
    const scoreTop = Object.entries(inv.scoreBreakdown).sort((a, b) => b[1] - a[1]);
    const strongest = scoreTop[0];
    const weakest = scoreTop[scoreTop.length - 1];

    const SCORE_LABELS: Record<string, string> = {
      indicationMatch: 'indication match', phaseExperience: 'phase experience',
      enrollmentVelocity: 'enrollment velocity', publicationVelocity: 'publication velocity',
      capacity: 'capacity signal', institutionalTrack: 'institutional track record',
      responsiveness: 'responsiveness', regulatoryRigor: 'regulatory rigor',
    };

    const msg = await anthropic.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 220,
      messages: [{
        role: 'user',
        content: `Write a 45-second investigator briefing for a clinical operations lead.

Rules: professional, efficient, no pleasantries, no headings, no stage directions. Plain prose only. Maximum 110 words.

Structure: Name and institution. Fit score and status. Strongest factor, weakest factor. Key trial history (1 trial). Capacity. Any 483 flags. Recommendation: reach out, defer, or exclude.

Data:
- Name: Dr. ${inv.name}, ${inv.credentials}
- Institution: ${inv.institution.name}, ${inv.city}, ${inv.country}
- Fit score: ${inv.fit}/100 (${inv.status})
- Active trials: ${inv.activeTrials} | Velocity: ${inv.velocity} enrollments/yr
- Indication: ${inv.indicationTags[0]}
- Strongest factor: ${SCORE_LABELS[strongest[0]] ?? strongest[0]} (${strongest[1]})
- Weakest factor: ${SCORE_LABELS[weakest[0]] ?? weakest[0]} (${weakest[1]})
- Recent trial: ${inv.recentTrials[0]?.title ?? 'none'} (${inv.recentTrials[0]?.role ?? ''})
- Publications: ${inv.publications.length} recent, top journal: ${inv.publications[0]?.journal ?? 'n/a'}
- 483 flag: ${inv.has483Flag ? 'YES — review required' : 'none'}
- Rising star: ${inv.isRisingStar ? 'yes' : 'no'}`
      }]
    });

    script = (msg.content[0] as { type: string; text: string }).text.trim();
  } catch (err) {
    console.warn('Claude script generation failed:', err);
    script = `Dr. ${inv.name} at ${inv.institution.name}. Fit score ${inv.fit}, status ${inv.status}. ${inv.activeTrials} active trials, ${inv.velocity} enrollments per year. ${inv.has483Flag ? 'FDA 483 flag on record — review required before outreach.' : 'No regulatory flags.'} ${inv.fit >= 85 ? 'Recommend immediate outreach.' : inv.fit >= 70 ? 'Consider outreach pending capacity review.' : 'Defer — capacity constraints noted.'}`;
  }

  // ── 2. Generate audio with ElevenLabs ───────────────────────────────────
  const elevenKey = process.env.ELEVENLABS_API_KEY;
  const voiceId   = process.env.ELEVENLABS_VOICE_ID ?? RACHEL_VOICE_ID;

  if (!elevenKey) {
    return NextResponse.json({ script, audioUrl: null, note: 'Set ELEVENLABS_API_KEY to enable audio' });
  }

  try {
    const elevenRes = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`, {
      method: 'POST',
      headers: {
        'xi-api-key': elevenKey,
        'Content-Type': 'application/json',
        Accept: 'audio/mpeg',
      },
      body: JSON.stringify({
        text: script,
        model_id: 'eleven_turbo_v2_5',
        voice_settings: { stability: 0.5, similarity_boost: 0.75 },
      }),
    });

    if (!elevenRes.ok) {
      console.error('ElevenLabs error:', await elevenRes.text());
      return NextResponse.json({ script, audioUrl: null });
    }

    const buf = await elevenRes.arrayBuffer();
    const audioUrl = `data:audio/mpeg;base64,${Buffer.from(buf).toString('base64')}`;

    cache.set(investigatorId, { script, audioUrl, ts: Date.now() });
    return NextResponse.json({ audioUrl, script });

  } catch (err) {
    console.error('ElevenLabs fetch error:', err);
    return NextResponse.json({ script, audioUrl: null });
  }
}
